import type { MetadataRoute } from 'next'

export default function sitemap(): MetadataRoute.Sitemap {
  return [
    { url: 'https://quickbg.dev', lastModified: new Date(), changeFrequency: 'weekly', priority: 1 },
    { url: 'https://quickbg.dev/about', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://quickbg.dev/tools', lastModified: new Date(), changeFrequency: 'weekly', priority: 0.9 },
    { url: 'https://quickbg.dev/remover', lastModified: new Date(), changeFrequency: 'weekly', priority: 0.9 },
    { url: 'https://quickbg.dev/replace-bg', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://quickbg.dev/blur-bg', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://quickbg.dev/resize', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://quickbg.dev/crop', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://quickbg.dev/adjust', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://quickbg.dev/sharpness', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://quickbg.dev/converter', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://quickbg.dev/faq', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://quickbg.dev/blog', lastModified: new Date(), changeFrequency: 'weekly', priority: 0.8 },
    { url: 'https://quickbg.dev/comparison', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://quickbg.dev/privacy', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.4 },
    { url: 'https://quickbg.dev/terms', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.4 },
    { url: 'https://quickbg.dev/legal', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.4 },
    { url: 'https://quickbg.dev/contact', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.5 },
    { url: 'https://quickbg.dev/blog/how-ai-background-removal-works', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: 'https://quickbg.dev/blog/transparent-pngs-amazon-etsy', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: 'https://quickbg.dev/blog/ecommerce-product-photos-guide', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: 'https://quickbg.dev/blog/best-free-image-editing-workflow', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: 'https://quickbg.dev/blog/common-mistakes-ai-background-removal', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: 'https://quickbg.dev/blog/how-to-resize-images-without-losing-quality-batch-processing-guide', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: 'https://quickbg.dev/blog/color-correction-101-adjusting-brightness-contrast-saturation', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: 'https://quickbg.dev/blog/image-sharpening-techniques-when-and-how-to-sharpen-photos', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: 'https://quickbg.dev/blog/complete-guide-to-cropping-rule-of-thirds-aspect-ratios-framing', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: 'https://quickbg.dev/blog/blur-effects-in-photography-background-vs-gaussian-vs-motion-blur', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: 'https://quickbg.dev/blog/how-to-create-amazon-approved-product-images-with-ai', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: 'https://quickbg.dev/blog/etsy-shop-optimization-role-of-image-quality-in-conversion', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: 'https://quickbg.dev/blog/diy-product-photography-professional-results-without-studio', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: 'https://quickbg.dev/blog/amazon-a-plus-content-transparent-cutouts-premium-listings', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: 'https://quickbg.dev/blog/multi-platform-selling-resizing-formatting-images-every-marketplace', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: 'https://quickbg.dev/blog/understanding-image-segmentation-semantic-vs-instance-vs-panoptic', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: 'https://quickbg.dev/blog/evolution-of-background-removal-chroma-key-to-deep-learning', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: 'https://quickbg.dev/blog/birefnet-vs-u2net-vs-modnet-comparing-ai-matting-models', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: 'https://quickbg.dev/blog/what-is-alpha-matte-and-why-it-matters-for-transparent-pngs', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: 'https://quickbg.dev/blog/science-of-image-resolution-dpi-ppi-and-why-size-matters', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: 'https://quickbg.dev/blog/quickbg-vs-removebg-which-background-removal-tool-is-better', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: 'https://quickbg.dev/blog/how-to-convert-images-between-formats-png-jpg-webp-avif', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: 'https://quickbg.dev/blog/ultimate-guide-to-quickbg-batch-processing-tools', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: 'https://quickbg.dev/blog/quickbg-vs-canva-background-removal-and-editing-compared', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: 'https://quickbg.dev/blog/quickbg-vs-adobe-photoshop-free-alternative-background-removal', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: 'https://quickbg.dev/blog/social-media-image-sizes-2026-complete-cheat-sheet', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: 'https://quickbg.dev/blog/creating-consistent-brand-imagery-instagram-tiktok', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: 'https://quickbg.dev/blog/how-to-build-image-processing-pipeline-online-store', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: 'https://quickbg.dev/blog/common-image-file-formats-explained-png-jpg-webp-avif', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: 'https://quickbg.dev/blog/10-image-editing-mistakes-that-hurt-your-conversion-rates', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
  ]
}
