steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_IMAGE_URI}
      - .

images:
  - ${_IMAGE_URI}

substitutions:
  _IMAGE_URI: us-central1-docker.pkg.dev/$PROJECT_ID/bgremover/bgremover-worker:latest
